#!/usr/bin/env sh

case $BLOCK_BUTTON in
	2) amixer -q -D pulse sset Master toggle ;;
	4) pactl set-sink-volume $(pacmd list-sinks | grep index | grep "*" | xargs | awk '{print $3}') +5% ;;
	5) pactl set-sink-volume $(pacmd list-sinks | grep index | grep "*" | xargs | awk '{print $3}') -5% ;;
	3) pgrep -x dunst >/dev/null && notify-send "📢 Volume module" "\- Shows volume 🔊, 🔇 if muted.
- Middle click to mute.
- Scroll to change."
esac

[ "$(pacmd list-sinks | awk '/^\smuted:/{i++} i=='$(pacmd list-sinks | awk '/index:/{i++} /* index:/{print i; exit}')'{print $2; exit}')" = "yes" ] && printf "🔇\\n" && exit

vol=$(pacmd list-sinks | awk '/^\svolume:/{i++} i=='$(pacmd list-sinks | awk '/index:/{i++} /* index:/{print i; exit}')'{print $5; exit}' | tr -d %)

if [ "$vol" -gt "70" ]; then
	icon="🔊"
elif [ "$vol" -lt "30" ]; then
	icon="🔈"
else
	icon="🔉"
fi

printf "%s %s%%\\n" "$icon" "$vol"
